### ISSUE TITLE
During the training process, the f1 score did not improve

### ISSUE THREAD

**Issue by zxzhang8** [hukuda222/code2seq#3]
Thank you for sharing the code, it helped me a lot. However, I used the java-small dataset and your parameters in run_small.sh to train more than a dozen epochs, and the F1 score did not improve. Do you have this situation? Because the GPU of my machine is not very good, an epoch will take a long time. I would like to ask if there will be changes if I continue to train.

**Comment by hukuda222** [comment]
At least in my environment, F1 score goes up in training. However, the result is lower than the score in the paper. I'm looking for the cause, but I'm still not quite sure what it is.
If you want to quickly replicate the score of the paper, I think you should refer to another implementation.

**Comment by zxzhang8** [comment]
Thanks for your reply, I am not in a hurry to replicate the F1 score in the paper. I just started and only learned pytorch, so your code has been very helpful to me.
Did you use "python main.py --trainpath train.h5 -g 0 --validpath valid.h5 --datapath java-small.dict.c2s -e 40 -b 256   --savename output --trainnum 691974 --validnum 23844"?
I used this to train, and F1 score never exceeds 0.5.
